/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterationRouteImport } from './routes/registeration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppLayoutRouteRouteImport } from './routes/_appLayout/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as AppLayoutProductsRouteImport } from './routes/_appLayout/products'
import { Route as AppLayoutAddCartRouteImport } from './routes/_appLayout/addCart'
import { Route as AppLayoutParticularProductIdRouteImport } from './routes/_appLayout/particularProduct.$id'
import { Route as AppLayoutCategoryProductsIdRouteImport } from './routes/_appLayout/categoryProducts.$id'

const RegisterationRoute = RegisterationRouteImport.update({
  id: '/registeration',
  path: '/registeration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutProductsRoute = AppLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutAddCartRoute = AppLayoutAddCartRouteImport.update({
  id: '/addCart',
  path: '/addCart',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutParticularProductIdRoute =
  AppLayoutParticularProductIdRouteImport.update({
    id: '/particularProduct/$id',
    path: '/particularProduct/$id',
    getParentRoute: () => AppLayoutRouteRoute,
  } as any)
const AppLayoutCategoryProductsIdRoute =
  AppLayoutCategoryProductsIdRouteImport.update({
    id: '/categoryProducts/$id',
    path: '/categoryProducts/$id',
    getParentRoute: () => AppLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/registeration': typeof RegisterationRoute
  '/addCart': typeof AppLayoutAddCartRoute
  '/products': typeof AppLayoutProductsRoute
  '/': typeof AppLayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/categoryProducts/$id': typeof AppLayoutCategoryProductsIdRoute
  '/particularProduct/$id': typeof AppLayoutParticularProductIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/registeration': typeof RegisterationRoute
  '/addCart': typeof AppLayoutAddCartRoute
  '/products': typeof AppLayoutProductsRoute
  '/': typeof AppLayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/categoryProducts/$id': typeof AppLayoutCategoryProductsIdRoute
  '/particularProduct/$id': typeof AppLayoutParticularProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/registeration': typeof RegisterationRoute
  '/_appLayout/addCart': typeof AppLayoutAddCartRoute
  '/_appLayout/products': typeof AppLayoutProductsRoute
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_appLayout/categoryProducts/$id': typeof AppLayoutCategoryProductsIdRoute
  '/_appLayout/particularProduct/$id': typeof AppLayoutParticularProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/registeration'
    | '/addCart'
    | '/products'
    | '/'
    | '/admin/'
    | '/categoryProducts/$id'
    | '/particularProduct/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/registeration'
    | '/addCart'
    | '/products'
    | '/'
    | '/admin'
    | '/categoryProducts/$id'
    | '/particularProduct/$id'
  id:
    | '__root__'
    | '/_appLayout'
    | '/admin'
    | '/login'
    | '/registeration'
    | '/_appLayout/addCart'
    | '/_appLayout/products'
    | '/_appLayout/'
    | '/admin/'
    | '/_appLayout/categoryProducts/$id'
    | '/_appLayout/particularProduct/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterationRoute: typeof RegisterationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registeration': {
      id: '/registeration'
      path: '/registeration'
      fullPath: '/registeration'
      preLoaderRoute: typeof RegisterationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/products': {
      id: '/_appLayout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppLayoutProductsRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/addCart': {
      id: '/_appLayout/addCart'
      path: '/addCart'
      fullPath: '/addCart'
      preLoaderRoute: typeof AppLayoutAddCartRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/particularProduct/$id': {
      id: '/_appLayout/particularProduct/$id'
      path: '/particularProduct/$id'
      fullPath: '/particularProduct/$id'
      preLoaderRoute: typeof AppLayoutParticularProductIdRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/categoryProducts/$id': {
      id: '/_appLayout/categoryProducts/$id'
      path: '/categoryProducts/$id'
      fullPath: '/categoryProducts/$id'
      preLoaderRoute: typeof AppLayoutCategoryProductsIdRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutAddCartRoute: typeof AppLayoutAddCartRoute
  AppLayoutProductsRoute: typeof AppLayoutProductsRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutCategoryProductsIdRoute: typeof AppLayoutCategoryProductsIdRoute
  AppLayoutParticularProductIdRoute: typeof AppLayoutParticularProductIdRoute
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutAddCartRoute: AppLayoutAddCartRoute,
  AppLayoutProductsRoute: AppLayoutProductsRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutCategoryProductsIdRoute: AppLayoutCategoryProductsIdRoute,
  AppLayoutParticularProductIdRoute: AppLayoutParticularProductIdRoute,
}

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterationRoute: RegisterationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
